# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

modGroup=com.ldtteam
modVersion=1.9
modId=storageracks
modBaseName=storageracks

forgeVersion=21.0.148
minecraftVersion=1.21
exactMinecraftVersion=1.21
additionalMinecraftVersions=

blockUI_version=1.21-1.0.160-BETA
dataGeneratorsVersion=0.1.54-ALPHA
domumOrnamentumVersion=1.21-1.0.195-BETA

jei_version=19.5.3.67
jei_mcversion=1.21

mappingsChannel=official
mappingsVersion=1.21

githubUrl=
gitUrl=
gitConnectUrl=
projectUrl=

curseId=

librarySourceSets=main;datagen;

javaVersion=21
useJavaToolChains=true

useDefaultTestSystem=false
runtimeSourceSets=main
projectHasApi=false
primaryJarClassifier=
isFMLLibrary=false
usesDatagen=true
usesResourceDataExpansionFromProjectKeys=false
