# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

modGroup=com.ldtteam
modVersion=1.11
modId=storageracks
modBaseName=storageracks
fml_range=[4,)
forgeVersion=21.1.20
minecraftVersion=1.21.1
exactMinecraftVersion=1.21.1
additionalMinecraftVersions=

forge_range=[21.0.143,)
minecraft_range=[1.21, 1.22)

blockUI_version=1.0.190-1.21.1-snapshot
dataGeneratorsVersion=0.1.54-ALPHA
domumOrnamentumVersion=1.0.204-1.21.1-snapshot

jei_version=19.19.0.220
jei_mcversion=1.21.1

mappingsChannel=official
mappingsVersion=1.21

githubUrl=
gitUrl=
gitConnectUrl=
projectUrl=

curseId=

librarySourceSets=main;datagen;

javaVersion=21
useJavaToolChains=true

useDefaultTestSystem=false
runtimeSourceSets=main
projectHasApi=false
primaryJarClassifier=
isFMLLibrary=false
usesDatagen=true
