configurations {
    library
    implementation.extendsFrom library
}

repositories {
    maven { url = 'https://files.minecraftforge.net/maven' }
    mavenLocal()
    mavenCentral()
    maven {
        name "JEI"
        url 'https://maven.blamejared.com/'
    }
    maven {
        url "https://plugins.gradle.org/m2/"
    }
    maven {
        name 'LDTTeam - Modding'
        url 'https://ldtteam.jfrog.io/ldtteam/modding/'
    }
}

dependencies {
    implementation ("com.ldtteam:blockui:${project.blockUI_version}")
    compileOnly (("com.ldtteam:domum-ornamentum:${project.domumOrnamentumVersion}")){
        transitive = false
    }
    runtimeOnly (("com.ldtteam:domum-ornamentum:${project.domumOrnamentumVersion}")){
        transitive = false
    }

    implementation ("com.ldtteam:datagenerators:1.19.3-${project.dataGeneratorsVersion}:universal") {
        transitive = false
    }

    runtimeOnly ("mezz.jei:jei-${project.jei_mcversion}-neoforge:${project.jei_version}")
}
